/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PreClinicalTrialRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sumanth
 */
public class PreClinicalTrialSelectPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PreClinicalTrialProcessJpanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    EcoSystem system;
    PreClinicalTrialSelectPersonJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        populatePersonTable();
    }
    
    void populatePersonTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblPreClinical.getModel();
        dtm.setRowCount(0);
        for(Person person: system.getPersonDirectory().getPersonList()){
            Object row[] = new Object[4];
            row[0] = person;
            row[1] = person.getAge();
            row[2] = person.getDisease();
            row[3] = person.getDiseaseList();
            dtm.addRow(row);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disTypComb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreClinical = new javax.swing.JTable();

        disTypComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPreClinical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Disease ", "Effects of Disease"
            }
        ));
        jScrollPane1.setViewportView(tblPreClinical);
        if (tblPreClinical.getColumnModel().getColumnCount() > 0) {
            tblPreClinical.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(disTypComb));
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 690, 212));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> disTypComb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPreClinical;
    // End of variables declaration//GEN-END:variables
}
