/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PostClinicalPubSecRole;

import Business.EcoSystem;
import Business.Person.Person;



import Business.Person.PersonDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class AddPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPersonJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    PersonDirectory personList;
    

   public AddPersonJPanel(JPanel userProcessContainer, EcoSystem system) {
    initComponents();
    
    this.userProcessContainer=userProcessContainer;
    
    this.system=system;
    
    this.personList=personList;
    
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameTxtField = new javax.swing.JTextField();
        ageTxtField = new javax.swing.JTextField();
        diseaseTxtField = new javax.swing.JTextField();
        addJButton = new javax.swing.JButton();
        cancelJbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 68, 26));

        jLabel2.setText("Age");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 68, 26));

        jLabel3.setText("Disease");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 68, 26));
        add(NameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 140, -1));

        ageTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtFieldActionPerformed(evt);
            }
        });
        add(ageTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 140, -1));
        add(diseaseTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 140, -1));

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        cancelJbutton.setText("Back");
        cancelJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJbuttonActionPerformed(evt);
            }
        });
        add(cancelJbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Add Person ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        

        String name = NameTxtField.getText();
        String disease = diseaseTxtField.getText();
        Integer age =0;
        
         try
       {                
            age = Integer.parseInt(ageTxtField.getText());
       }
       catch(NumberFormatException e)
       {
           JOptionPane.showMessageDialog(null, "Please enter a valid Integer");
       } 
        
         if(name.equalsIgnoreCase("") || ageTxtField.getText().equalsIgnoreCase("") || disease == null ){
            JOptionPane.showMessageDialog(null, "Please enter valid details", "Invalid Details", JOptionPane.ERROR_MESSAGE);
            return;
        }
         else 
         {
             Person person = system.getPersonDirectory().addPerson();
             person.setName(name);
             person.setAge(age);
             person.setDisease(disease);
            
            JOptionPane.showMessageDialog(null,"Person Successfully created."); 
            NameTxtField.setText("");
            ageTxtField.setText("");
            diseaseTxtField.setText("");
             
         }
        
        
    }//GEN-LAST:event_addJButtonActionPerformed

    private void ageTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtFieldActionPerformed

    private void cancelJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJbuttonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PostClinicalPubSecJPanel manageperson = (PostClinicalPubSecJPanel) component;
        //manageperson.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_cancelJbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTxtField;
    private javax.swing.JButton addJButton;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton cancelJbutton;
    private javax.swing.JTextField diseaseTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
