/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PharmaRole;

import Business.Disease.Disease;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.Request.Request;
import UserInterface.AdministrativeRole.ManageUserAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sumanth
 */
public class PharmaWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization clinicOrganization;
    Enterprise enterprise;
    EcoSystem system;

    public PharmaWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization clinicOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.clinicOrganization = clinicOrganization;
        this.enterprise = enterprise;
        this.system = system;
        enterPrText.setText(enterprise.getName());
        orgText.setText(clinicOrganization.getName());
        empNameTxt.setText(account.getEmployee().getName());
        vaccineTxt.setText(account.getEmployee().getVaccine().getvName());
        diseaseTxt.setText(account.getEmployee().getDisease().getdName());
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (Request request : account.getRequestList().getRequestList()){
            Object[] row = new Object[4];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            row[3] = request.getResult();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkBtn = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        empNameTxt = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        enterPrText = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        orgText = new javax.swing.JLabel();
        diseaseTxt = new javax.swing.JTextField();
        vaccineTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Disease:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 60, 40));

        jLabel2.setText("Vaccine:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 80, 40));

        checkBtn.setBackground(new java.awt.Color(204, 255, 0));
        checkBtn.setForeground(new java.awt.Color(0, 51, 51));
        checkBtn.setText("Send request about drug manufacture");
        checkBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 153), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });
        add(checkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 280, 50));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("Employee Name:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        empNameTxt.setText("<Value>");
        add(empNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 120, 20));

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("EnterPrise :");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        enterPrText.setText("<value>");
        add(enterPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 20));

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel2.setText("Organization:");
        add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, -1));

        orgText.setText("<value>");
        add(orgText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 120, 20));

        diseaseTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 153), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));
        diseaseTxt.setEnabled(false);
        add(diseaseTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 110, 30));

        vaccineTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 153), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0), new java.awt.Color(255, 255, 0)));
        vaccineTxt.setEnabled(false);
        add(vaccineTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 110, 30));

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 630, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Pharma Work Area");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 440, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        Disease disease = account.getEmployee().getDisease();
        Vaccine vaccine = account.getEmployee().getVaccine();
        PharmaRequestJPanel muajp = new PharmaRequestJPanel(userProcessContainer, account, clinicOrganization, enterprise, system,disease,vaccine);
                userProcessContainer.add("PharmaRequestJPanel", muajp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
    }//GEN-LAST:event_checkBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkBtn;
    private javax.swing.JTextField diseaseTxt;
    private javax.swing.JLabel empNameTxt;
    private javax.swing.JLabel enterPrText;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orgText;
    private javax.swing.JTextField vaccineTxt;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
